rbp:
  name:                 'rails_best_practices'
  weight:               1
  command:              'rails_best_practices --without-color --with-urls .'
  problem_pattern:      '^\S.+:\d+.+$'
  filename_pattern:     '^\.\/(.+):\d'
  line_number_pattern:  '^.+:(\d+)'
  description_pattern:  '\s-\s(.+)$'

cleanup:
  name:                 'cleanup'
  weight:               5
  command:              "grep -r -n '#CLEANUP:' app/controllers app/helpers app/models lib | awk '{n = substr($0, match($0, /[0-9]+:/), RLENGTH) + 1; sub(/[0-9]+:/, n); print }'"
  problem_pattern:      '^\S.+:\d+.+$'
  filename_pattern:     '^(.+):\d'
  line_number_pattern:  '^.+:(\d+)'
  description_pattern:  '#CLEANUP:\s(.+)$'

# reek:
#   name:                 'reek'
#   weight:               0.8
#   command:              "reek -y -c config/defaults.reek app/controllers app/helpers app/models lib"
#   problem_pattern:      '!([^!]+)'
#   filename_pattern:     'source:\s(.+)$'
#   line_number_pattern:  '- (\d+)'
#   description_pattern:  'subclass:\s(.+)call'
